#!/bin/sh

text=""
read_option() {
	exp=""
	if [ "$2" != "" ]
	then
		exp=" ($2)"
	fi
	echo -n "$1$exp: "
	read text
	if [ "$text" = "" ]
	then
		text="$2"
	fi
}

echo "Welcome to Nelio Plugin Boilerplate."
echo "Let's create your new plugin!"

name=""
dir=""
prefix=""

ok="n"
verbose="y"
while [ "$ok" = "n" ]
do
	echo ""

	echo "Plugin Information"
	# ===================================================
	read_option "  Plugin Name" "$name"
	name=$text

	read_option "  Current Version" "$version"
	version=$text

	read_option "  Plugin Dir" "$dir"
	dir=$text

	read_option "  Class Prefix" "$prefix"
	prefix=$text

	echo "Author Information"
	# ===================================================
	read_option "  Author Name" "$author"
	author=$text

	read_option "  Author E-Mail" "$email"
	email=$text

	echo ""
	echo "Please, check the information your provided:"
	echo ""
	echo "  Plugin Name:  $name"
	echo "  Version:      $version"
	echo "  Plugin Dir:   $dir"
	echo "  Class Prefix: $prefix"
	echo ""
	echo "  Author: $author <$email>"
	echo ""
	echo -n "Is everything OK? (Y/n) "
	read ok
done

echo ""

# Prepare some variables
domain=`echo "$prefix" | tr "[:upper:]" "[:lower:]"`
slug=`echo "$domain" | sed -e "s/_/-/"`

# Create the new plugin
cp -r "plugin-name" "$dir"

# Rename all files
mv "$dir/plugin-name.php" "$dir/${slug}.php" 2>/dev/null
find $dir -type "f" | while read file
do
	dest=`echo "$file" | sed -e "s/plugin-name/$slug/"`
	mv "$file" "$dest" 2>/dev/null
done

# Make the appropriate changes in the contents
find $dir -type "f" | while read file
do
	cat "$file" | \
		sed -e "s/1.0.0/$version/g" | \
		sed -e "s/Plugin Name/$name/g" | \
		sed -e "s/* $name:/* Plugin Name:/g" | \
		sed -e "s/Plugin_Name/$prefix/g" | \
		sed -e "s/plugin_name/$domain/g" | \
		sed -e "s/plugin-name/$slug/g" | \
		sed -e "s/Your Name/$author/g" | \
		sed -e "s/your.name@example.com/$email/g" > "$dir/aux"
	mv "$dir/aux" "$file"
done
